### ISSUE TITLE
Installing TeNeS / user-defined model & lattice

### ISSUE THREAD

**Issue by HamidArianZad** [issp-center-dev/TeNeS#43]
Dear TeNeS team,

I installed TeNeS on ubuntu 16.04.
I installed c++11 compiler and Cmake 3.12
I install numpy and other packages of python3 including toml

First, I could not install the TeNeS in build folder. I followed below steps.
1. $ git clone https://github.com/issp-center-dev/TeNeS
2. $ mkdir build
3. $ cd build
4. $ cmake  -DCMAKE_INSTALL_PREFIX=/usr/azam ..
Then I got the below error:
     CMake Error: The source directory "/home/azam" does not appear to contain CMakeLists.txt.
     Specify --help for usage, or press the help button on the CMake GUI.

But I moved the folder build to TeNeS folder and run:
   cd TeNeS
   cd build
   $ cmake  -DCMAKE_INSTALL_PREFIX=/usr/azam ..
Then I got attached building confirmation.
![TeNeS_1](https://user-images.githubusercontent.com/97589591/150618398-e32f8ebd-4280-4cdd-95e3-b41a78115198.png)

After that I tried to make TeNeS by following command:
$ make install 
but I got error (attachment)
![TeNeS2](https://user-images.githubusercontent.com/97589591/150618707-0db0bdd8-6b84-4f9d-b098-ae404fdf8c97.png)

Then, I tried 
$ sudo make install 
and I got following installing explanation:
![TeNeS3](https://user-images.githubusercontent.com/97589591/150618917-040fcfc4-e88e-435e-89f0-fe2ef7959870.png)
 
Next, I tried to run: python3 tutorial_magnetization.py 
I got error: python3 can't open file 'tutorial_magnetization.py': [Error 2] No such file or directory
I receive the same error when I run other tutorials.

I do not know what is the problem. I will be very thankful to you if help me to solve that.

Thank you
Hamid

**Comment by k-yoshimi** [comment]
@HamidArianZad 
This command error appears to be caused by the fact that the python command is not running in the directory ``TeNeS/sample/05_magnetization`` where ``tutorial_magnetization.py`` is located.
If you did not move to the directory, please change the directory and run the command again.

**Comment by HamidArianZad** [comment]
> @HamidArianZad This command error appears to be caused by the fact that the python command is not running in the directory `TeNeS/sample/05_magnetization` where `tutorial_magnetization.py` is located. If you did not move to the directory, please change the directory and run the command again.

Dear yoshimi,
Thank you very much. I could run the codes and plot the magnetization for various models.
I have a query and I will be thankful to you is answer.
QUERY:
I want to simulate the magnetization of a triangular lattice including two-body and three-body interactions that is in the presence of an external magnetic field H. Does the TeNeS support such a calculation? 
Should I introduce my own lattice manually by changing fome lines of the tenes_simple.py and tenes_std.py files?
The Hamiltonian of my favorite model is presented in attachment.
![Hamiltonian](https://user-images.githubusercontent.com/97589591/150735108-b310bafc-9d20-42e2-b1ab-16feb554c3ee.png)

**Comment by yomichi** [comment]
@HamidArianZad 
Please make a new issue for another problem/question

**Comment by HamidArianZad** [comment]
Hi
I want to simulate the magnetization of an Ising triangular lattice including two-body and three-body interactions that is in the presence of an external magnetic field H. Does the TeNeS support such a calculation?
Should I introduce my own lattice manually by changing fome lines of the tenes_simple.py and tenes_std.py files?
The Hamiltonian of my favorite model is presented in attachment.
![Hamiltonian](https://user-images.githubusercontent.com/97589591/150740343-709b0f75-dfd9-4ee2-b65e-1bdf3665fffa.png)

**Comment by yomichi** [comment]
This Hamiltonian looks like a classical Ising model, doesn't it? If so, it may be better to use another software package (but I'm sorry I don't know a suitable program)

Anyway, TeNeS potentially can treat three or more body systems.
TeNeS accepts the series of imaginary-time evolutional tensors on nearest-neighbor bonds of the square lattice as the input.
We can always split the imaginary-time evolutional tensor U = exp(-tau Si Sj Sk) into the series of two-body imaginary-time evolutionally tensors acting on nearest-neighbor bond on the square lattice as U = U1 ... Un by using some tensor decomposition technique such as SVD.
Indeed, TeNeS treats a nearest-neighbor model on a triangular lattice as a long-ranged model on a square lattice, by inserting an identity operator acting on middle sites.

For the current version of TeNeS, unfortunately, we cannot specify the multi-site operators such as SiSjSk for calculating the expectation value, and hence we can search for the ground state of the three-body system but cannot evaluate the energy.

**Comment by HamidArianZad** [comment]
> This Hamiltonian looks like a classical Ising model, doesn't it? If so, it may be better to use another software package (but I'm sorry I don't know a suitable program)
> 
> Anyway, TeNeS potentially can treat three or more body systems. TeNeS accepts the series of imaginary-time evolutional tensors on nearest-neighbor bonds of the square lattice as the input. We can always split the imaginary-time evolutional tensor U = exp(-tau Si Sj Sk) into the series of two-body imaginary-time evolutionally tensors acting on nearest-neighbor bond on the square lattice as U = U1 ... Un by using some tensor decomposition technique such as SVD. Indeed, TeNeS treats a nearest-neighbor model on a triangular lattice as a long-ranged model on a square lattice, by inserting an identity operator acting on middle sites.
> 
> For the current version of TeNeS, unfortunately, we cannot specify the multi-site operators such as SiSjSk for calculating the expectation value, and hence we can search for the ground state of the three-body system but cannot evaluate the energy.

**Comment by HamidArianZad** [comment]
Yes, this is a classical Ising model. Thank you for recommending another package. I am using metropolis algorithm (mc simulations) to do that.

I also want to simulate the magnetization of a full Heisenberg model on a specific 2D lattice so-called martini lattice as attached figure with the corresponding Hamiltonian.
Can I benefits TeNeS to do that? If so, please let me know from what part of TeNeS package I should start to manually change?
![MartiniLattices](https://user-images.githubusercontent.com/97589591/150747771-cbd41881-0729-4dfe-b92e-3c2729a5d533.png)
Thanks!!

**Comment by yomichi** [comment]
You can define this lattice model by using standard mode (`tenes_std`).
https://issp-center-dev.github.io/TeNeS/manual/master/en/html/file_specification/standard_format.html

`tensor` section defines sites (shape of the unitcell, dimension of virtual bonds, ...), and `hamiltonian` section defines bonds (and bond hamiltonians acting on these bonds)

A kagome lattice may be helpful for making a new lattice.
https://issp-center-dev.github.io/TeNeS/manual/master/en/html/file_specification/simple_format.html
2x2x3 sites kagome lattice is represented on the square lattice as Fig. 5.4 (e).

To see the sample standard mode's input file representing kagome lattice, save the following as `simple.toml`

```
[parameter]
[parameter.general]

[parameter.simple_update]
num_step = 1000
tau = 0.01

[parameter.full_update]
num_step = 0
tau = 0.01

[lattice]
type = "kagome lattice"
L = 2
W = 2
initial = "ferro"
virtual_dim = 2

[model]
type = "spin"
J = 1.0
```

and pass it to `tenes_simple` to generate `std.toml` (an input file of `tenes_std`).

**Comment by HamidArianZad** [comment]
Dear yomichi,

Thank you very much for your information.
I am trying too define my own lattice in TeNeS.
Could you please let me know that for how many particles I can run my own code to obtain the magnetization versus magnetic field?
My system is MSI laptop: core i7-11th , Ram 16g and 512 SSD hard disk.

Thanks!!

**Comment by HamidArianZad** [comment]
Dear TeNeS team,

I changed the bonds of kagome lattice class in tenes_simple file (see attachment).
![Kagome_Martini_bonds](https://user-images.githubusercontent.com/97589591/154792011-8003909a-7286-4fb8-a62d-c7d6caf9f9fc.png)

I also created a simple.toml file as you recommended in previous massages. I could simulate the magnetization of the martini lattice 1 (shown in attached figure above) but I received a warning about ctm.
I found that in the simple.toml and basic.toml files of the sample models such as AFM square lattice and triabgular lattice you defined:
[parameter.ctm]
iteration_max = 100
dimension = 10
I added this definition to the simple.toml file and in the simple_0_2000.toml file I got:
[lattice]
type = "kagome lattice"
L = 2
W = 2
initial = "ferro"
virtual_dim = 2

[model]
type = "spin"
J = 1.0
hz = 0.0

[parameter.general]
output = "output_0_2000"
tensor_save = "tensor_save"

[parameter.simple_update]
num_step = 2000
tau = 0.01

[parameter.full_update]
num_step = 0
tau = 0.01

[parameter.ctm]
iteration_max = 100
dimension = 10

I would like to know for how many sites I got the below magnetization?

![mag_martini lattice 1_J1](https://user-images.githubusercontent.com/97589591/154808614-195b3a91-b198-4d80-bce1-6db28de4d942.png)

below is the coordinate.dat:
# coord_version = 1
# name = kagome lattice
# a0 = 4.0 0.0
# a1 = 2.0 3.4641016151377544
# $1: index
# $2: x
# $3: y

0 0.0 0.0
1 1.0 0.0
2 2.0 0.0
3 3.0 0.0
4 0.5 0.8660254037844386
6 2.5 0.8660254037844386
8 1.0 1.7320508075688772
9 2.0 1.7320508075688772
10 3.0 1.7320508075688772
11 4.0 1.7320508075688772
12 1.5 2.598076211353316
14 3.5 2.598076211353316

I think for 14 sites I got the results for the magnetization, if so, why sites 5 and 13 has been omitted?

Also I can see that the TeNeS could reproduce nicely the intermediate magnetization plateau at M/M_s = 1/6 with the magnetization jumps nearby the critical magnetic fields B=0.84 and B=1.5. But other plateaus are not created.
How can I resolve the problem. The ground-state phase transition of the martini lattice 1 is shown in bellow attached figure:
![Martini1_GSPD](https://user-images.githubusercontent.com/97589591/154809103-08cfa68f-eeaa-421b-aff5-5b3b0174447a.png)

Thanks!
