### ISSUE TITLE
Date of ver.1.2.0

### ISSUE THREAD

**Issue by HamidArianZad** [issp-center-dev/TeNeS#57]
Dear TeNeS organizers,

I think there is a mistake in the date of updated version ver.1.2.0. It should be 2021-12-13.
![Version](https://user-images.githubusercontent.com/97589591/192226254-82070738-c8cf-4095-b25a-c2187429c4b4.png)

**Comment by yomichi** [comment]
Thank you for reporting, I fixed it.
