### ISSUE TITLE
Initialization as antiferromagnetic state for S=1

### ISSUE THREAD

**Issue by TsuyoshiOkubo** [issp-center-dev/TeNeS#61]
I realized that the initialization of tensors generated by tenes_simple probably needs to be corrected for, at least, the S=1 model. 
When we set S=1 and
>initial = "antiferro" 

We see two spin states as the initial state in std.toml created by tense_simple:
> initial_state = [1.0, 0.0, 0.0]
> initial_state = [0.0, 1.0, 0.0]

Calculating the expectation value for this initial state shows that it is not the expected antiferromagnetic state. Probably, the latter state is |0>. I think the initial_state should be

> initial_state = [1.0, 0.0, 0.0]
> initial_state = [0.0, 0.0, 1.0]

**Comment by yomichi** [comment]
Thank you for reporting, I fixed it in PR #62, which is merged into the develop branch.
