### ISSUE TITLE
tenes error in running samples

### ISSUE THREAD

**Issue by HamidArianZad** [issp-center-dev/TeNeS#72]
Dear TeNeS developers,

Recently, I installed new version of TeNeS (v-1.3.3) on my notebook.
When I try to run the sample files for example: `tutorial_magnetization.py`  in the `TeNeS/sample/05-magnetization` folder I get error:

``
(base) hamid@hamid-ASUS-TUF-Dash-F15-FX517ZM-TUF517ZM:~/TeNeS/sample/05_magnetization$ python tutorial_magnetization.py
Calculation Process: 1/21
Steps: 100
tenes: error while loading shared libraries: libmpi.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/hamid/TeNeS/sample/05_magnetization/tutorial_magnetization.py", line 60, in <module>
    with open(join(output_dir, "density.dat")) as f:
``

Can you please let me know where is the problem?

I have had previous versions (v-1.2.0 and v-1.3.0) on my notebook they were working normally.

**Comment by HamidArianZad** [comment]
I found that in file CmakeList.txt, versions of cmake is restricted by command line: `cmake_minimum_required(VERSION 3.6...3.14)`.
Hence, I used cmake v-3.12.1, and I could successfully install new version of TeNeS on one of my notebooks (HP-ProBook-4530s), and it works well.
But on the other notebook (Asus-TUF-Dash-F15) with the same operating system, Ubuntu mint 21, I get below error when I run the command `python3 tutorial_magnetization.py`:

```
python3 tutorial_magnetization.py
Calculation Process: 1/21
Steps: 100
Traceback (most recent call last):
  File "/home/hamid/TeNeS/sample/05_magnetization/tutorial_magnetization.py", line 50, in <module>
    subprocess.call(cmd.split())
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tenes_simple'
```
The TeNeS has been installed successfully and I can see tenes_std and tenes_simple files in directory `/home/hamid/bin`.
It is surprising that, I did the same procedure with the same cmake version in my older laptop HP-Probook-4530s with Ubuntu mint 21 operating system, TeNeS works normally. 
But in my new laptop Asus-TUF-Dash-F15 I get above error.

Can you please let me know where is the problem?

**Comment by yomichi** [comment]
Is this issue solved? If so, please close it.

**Comment by HamidArianZad** [comment]
Yes,
Thanks!
