### ISSUE TITLE
An error : On entry to DGEMM parameter number 10 had an illegal value

### ISSUE THREAD

**Issue by sunzhaoyu2000** [issp-center-dev/TeNeS#96]
Dear developers and users,

When I try to simulate a 2D transverse-field Ising model,
with several magnetic fields,
the following error is reported:
--------------------------------
Start calculating observables   
 Start updating environment   
 Start calculating onesite operators     
 Save onesite observables to output/onesite_obs.dat   
 Start calculating twosite operators     
 Save twosite observables to output/twosite_obs.dat   
 Start calculating multisite operators   
 Start calculating correlation length  
** On entry to DGEMM parameter number 10 had an illegal value
--------------------------------

Is there some methods to solve this error?
Any suggestions would greatly helpful.

**Comment by sunzhaoyu2000** [comment]
My input file "simple.toml" is as follows:
---------------------------------------------------------------
[parameter]
[parameter.general]
is_real = true  # Limit tensor elements in real (not complex)
tensor_save = "tensor" # save all tensors into this directory

[parameter.simple_update]
num_step = 0          # Number of steps in simple update
tau = 0.1            # Imaginary time slice

[parameter.full_update]
num_step = 100        # Number of steps in full update // it is necessary to use FFU to save iTPS
tau =  0.1             # Imaginary time slice

[parameter.ctm]
meanfield_env = false   # Use meanfield environment to contract iTNS
iteration_max = 100     # Maximum number of iterations in CTMRG
dimension = 30          # Bond dimension of corner transfer matrix


[lattice]
type = "square lattice" # Type of lattice
L = 2                   # X length of unit cell
W = 2                   # Y length of unit cell
virtual_dim = 3         # Bond dimension of bulk tensors
initial = "random"       # Initial condition

[model]
type = "spin" # Type of model
Jz =  0.0      # Jz SzSz
Jx = -1.0      # Jx SxSx
Jy =  0.0      # Jy SySy
hz = 0.60

-------------------------------------------------------------


My commands are as follows:
-------------------------------
tenes_simple simple.toml
tenes_std std.toml
tenes input.toml
-------------------------------


The complete output is as follows
------------------------------
INFO: observable.multisite is not found in the input file. (Skipped)
Number of MPI Processes: 1
Number of OpenMP Threads of each MPI Process: 1
Tensor type: real
Bond dimensions:
   D  (Bulk): 3
   chi (CTM): 30
Start simple update
Start full update
  10% [10/100] done
  20% [20/100] done
  30% [30/100] done
  40% [40/100] done
  50% [50/100] done
  60% [60/100] done
  70% [70/100] done
  80% [80/100] done
  90% [90/100] done
  100% [100/100] done
Tensors saved in tensor
Start calculating observables
  Start updating environment
  Start calculating onesite operators
    Save onesite observables to output/onesite_obs.dat
  Start calculating twosite operators
    Save twosite observables to output/twosite_obs.dat
  Start calculating multisite operators
  Start calculating correlation length
 ** On entry to DGEMM parameter number 10 had an illegal value
------------------------------

Is it possible to close the option about calculating correlation length ?
It seems that this error is related to calculate correlation length.

**Comment by k-yoshimi** [comment]
The calculation using your input file was completed successfully in my environment.
Could you provide information on the TeNeS version and the memory used in the calculation?

**Comment by sunzhaoyu2000** [comment]
> The calculation using your input file was completed successfully in my environment. Could you provide information on the TeNeS version and the memory used in the calculation?

Dear k-yoshimi,

The command
`$ tenes --version`
gives
`TeNeS v2.0.0`



May I ask what do you mean by "provide memory used in the calculation" ?



When I change the parameter
```
[parameter.full_update]
num_step = 100        
tau =  0.1 
```           
into
```
[parameter.full_update]
num_step = 1000       
tau =  0.01  
```          
the error disappears.


By the way,
With num_step = 100  and tau =  0.1,
this error has been reproduced many times in my computer.

**Comment by k-yoshimi** [comment]
We think that the memory used in this calculation may be overloaded. However, this does not appear to be the cause of the failure, as calculations in similar situations have been successful.

The latest version of TeNeS is v.2.1.0, which fixes some errors.
https://github.com/issp-center-dev/TeNeS/releases/tag/v2.1.0
Could you try to perform the calculation using this version ?

**Comment by sunzhaoyu2000** [comment]
> We think that the memory used in this calculation may be overloaded. However, this does not appear to be the cause of the failure, as calculations in similar situations have been successful.
> 
> The latest version of TeNeS is v.2.1.0, which fixes some errors. https://github.com/issp-center-dev/TeNeS/releases/tag/v2.1.0 Could you try to perform the calculation using this version ?

Dear [k-yoshimi](https://github.com/k-yoshimi)

I am writing to confirm that this error indeed disappears when TeNeS is updated from 2.0.0 to 2.1.0. 
Thank you very much for your guidance.
